# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build corne xiao ble'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["seeeduino_xiao_ble"]'
      shield: '["corne_left","corne_right"]'
      alphas: '["workman"]'
      branches: '["zmkfirmware/zmk/main"]'
      mapping: '["miryoku/mapping/42/corne.h"]'
